settings:
  default-lang: "en"
  mongo-uri: "mongodb://localhost/minecraft"
  redis-uri: "redis://localhost:6379/0"

cache:
  enabled: true
  time-after-read: 120
  time-after-write: 120

parties:
  disband-timeout: 5
  max-members: 10

requests:
  expiration: 300
  cooldown-after-deny: 600
  actions:
    accept:
      text: "i18n:common.accept"
      command: "/party accept {party}"
    deny:
      text: "i18n:common.deny"
      command: "/party deny {party}"
    # custom:
    #   text: "text:&8[&e&lIgnore&8]"
    #  command: "/ignore {source}"