#    ___       _                                       _ ______               _    _            
#   / _ \     | |                                     | || ___ \             | |  (_)           
#  / /_\ \  __| |__   __  __ _  _ __    ___   ___   __| || |_/ /  __ _  _ __ | |_  _   ___  ___ 
#  |  _  | / _` |\ \ / / / _` || '_ \  / __| / _ \ / _` ||  __/  / _` || '__|| __|| | / _ \/ __|
#  | | | || (_| | \ V / | (_| || | | || (__ |  __/| (_| || |    | (_| || |   | |_ | ||  __/\__ \
#  \_| |_/ \__,_|  \_/   \__,_||_| |_| \___| \___| \__,_|\_|     \__,_||_|    \__||_| \___||___/
#                                                                                               
#   Created by Sammwy (2LStudios-MC)
#     - Source Code: https://github.com/2lstudios-mc/AdvancedParties
#     - Support: https://discord.gg/rWKXyJr

# General plugin settings.
settings:
  # The default language in case of not finding a suitable translation (also for console)
  default-lang: "en"
  # This plugin requires MongoDB to store data across different servers.
  mongo-uri: "mongodb://localhost/minecraft"
  # This plugin requires Redis to send data across different servers.
  redis-uri: "redis://localhost:6379/0"

# Cache settings.
cache:
  # Parties in the database can be cached to reduce the number of queries.
  enabled: true
  # The time in seconds that a party is stored in ram after being readed.
  time-after-read: 120
  # The time in seconds that a party is stored in ram after being written.
  time-after-write: 120

# Party settings.
parties:
  # The time (in seconds) that must pass after the leader of a party leaves the server to dissolve it.
  disband-timeout: 30
  # The maximum number of members allowed per party.
  max-members: 10

# Requests settings.
requests:
  # The time (in seconds) for expiry of party invitations.
  expiration: 300
  # The amount of time that must pass after a player declines an invitation before they can be invited again.
  cooldown-after-deny: 600
  # The clickable actions when receiving an invitation to a party.
  # Customizable actions are also allowed.
  actions:
    accept:
      text: "i18n:common.accept"
      command: "/party accept {party}"
    deny:
      text: "i18n:common.deny"
      command: "/party deny {party}"
    # custom:
    #   text: "text:&8[&e&lIgnore&8]"
    #  command: "/ignore {source}"