settings:
  default-lang: "en"
  gc-time: 43200
  mongo-uri: "mongodb://localhost/minecraft"
  redis-uri: "redis://localhost/0"

cache:
  enabled: true
  time-after-read: 120
  time-after-write: 120

parties:
  max-members: 10

requests:
  expiration: 30