name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  advancedparties:
    aliases: ["party"]
    description: "Main parties command"