name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depend: ["Milkshake-Bukkit", "Jedis"]
softdepend: ["PlaceholderAPI", "InterfaceMaker", "Skywars"]
api-version: 1.18
commands:
  advancedparties:
    aliases: ["party"]
    description: "Main parties command"