name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depends: ["Milkshake-Bukkit", "Jedis"]
softdepends: ["PlaceholderAPI", "InterfaceMaker"]
commands:
  advancedparties:
    aliases: ["party"]
    description: "Main parties command"